[[UNRESOLVED_REF]]
id = "TWEAKXL_11004"
span_starts_with = "TweakXL"
message = "Install TweakXL 1.10.4 or higher"

[[UNRESOLVED_REF]]
id = "TWEAKXL_11004"
span_starts_with = "TweakDBManager"
message = "Install TweakXL 1.10.4 or higher"

[[UNRESOLVED_REF]]
id = "CODEWARE_11206"
span_starts_with = "Codeware"
message = "Install Codeware 1.12.6 or higher"
