[[UNRESOLVED_REF]]
id = "TWEAKXL_11007"
span_starts_with = "TweakXL"
message = "Install TweakXL 1.10.7 or higher"

[[UNRESOLVED_REF]]
id = "TWEAKXL_11007"
span_starts_with = "TweakDBManager"
message = "Install TweakXL 1.10.7 or higher"

[[UNRESOLVED_REF]]
id = "CODEWARE_11500"
span_starts_with = "Codeware"
message = "Install Codeware 1.15.0 or higher"
